import type { Metadata } from "next";
import { Geist, Geist_Mono,  Playfair_Display, Inter } from "next/font/google";
import Header from "./(component)/Header";
import Footer from "./(component)/Footer";
import "./globals.css";
import Copyright from "./(component)/Copyright";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YES PARK CAFE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${inter.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
        <Copyright />
      </body>
    </html>
  );
}
